In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_excel('FY22.xlsx', sheet_name='FY22')

In [3]:
df.head()

,2022 BF Data Pull (BF Lines Only),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23
0,Portfolio,Congressional Program,Investment,Congressional Project,Sub-Project,Q#1. Sub-Project Description [BF Line],Q#6. Sub-Project Risks [BF Line],IT Tower [BF Line],IT Sub-Tower [BF Line],Cost Pool [BF Line],...,Line Item # [BF Line],Status,Strip Type,OIT Priority,SOC,Sub-Account,Type Summary,$ BY MYP Amount,$ BY OMB Submission Amount,$ BY OMB Passback Amount
1,Administrative,Corporate Operations and Maintenance,Administrative,IT Support Contracts,Ann Arbor,Ann Arbor - Location at 24 Frank Lloyd Wright ...,NaN,IT Management,IT Finance,Facilities & Power,...,45,No BY Funds,Sustainment-Steady-State,Operations and Maintenance,2328,OM,IT Support Contracts [other than PMO and Appli...,0,0,0
2,Administrative,Corporate Operations and Maintenance,Administrative,IT Support Contracts,Arlington OIT Power VA-549R-46-07,"Department of Veterans Affairs (VA), Office of...",NaN,IT Management,IT Finance,Facilities & Power,...,48,No BY Funds,Sustainment-Steady-State,Operations and Maintenance,2528,OM,IT Support Contracts [other than PMO and Appli...,0,0,0
3,Administrative,Corporate Operations and Maintenance,Administrative,IT Support Contracts,Arlington OIT VA-549R-30-02,"Department of Veterans Affairs (VA), Office of...",NaN,IT Management,IT Finance,Facilities & Power,...,46,No BY Funds,Sustainment-Steady-State,Operations and Maintenance,2328,OM,IT Support Contracts [other than PMO and Appli...,0,0,0
4,Administrative,Corporate Operations and Maintenance,Administrative,IT Support Contracts,Arlington OIT VA-549R-46-07,"Department of Veterans Affairs (VA), Office of...",NaN,IT Management,IT Finance,Facilities & Power,...,47,No BY Funds,Sustainment-Steady-State,Operations and Maintenance,2328,OM,IT Support Contracts [other than PMO and Appli...,0,0,0

In [8]:
# do I know what will columns will be filtered? 
# 'Status' = 'Financed'
# 'Funding Type' = 'BA'
# 'Portfolio' = 'Administrative'

In [4]:
# Is there a column that I can use as an Index column?

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1568 entries, 0 to 1567
Data columns (total 24 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   2022 BF Data Pull (BF Lines Only)  1567 non-null   object
 1   Unnamed: 1                         1563 non-null   object
 2   Unnamed: 2                         1567 non-null   object
 3   Unnamed: 3                         1563 non-null   object
 4   Unnamed: 4                         1563 non-null   object
 5   Unnamed: 5                         1558 non-null   object
 6   Unnamed: 6                         566 non-null    object
 7   Unnamed: 7                         1563 non-null   object
 8   Unnamed: 8                         1563 non-null   object
 9   Unnamed: 9                         1563 non-null   object
 10  Unnamed: 10                        1563 non-null   object
 11  Unnamed: 11                        1567 non-null   object
 12  Unnamed: 12                        1567 non-null   object
 13  Unnamed: 13                        1567 non-null   object
 14  Unnamed: 14                        1563 non-null   object
 15  Unnamed: 15                        1563 non-null   object
 16  Unnamed: 16                        1563 non-null   object
 17  Unnamed: 17                        1563 non-null   object
 18  Unnamed: 18                        1563 non-null   object
 19  Unnamed: 19                        1563 non-null   object
 20  Unnamed: 20                        1558 non-null   object
 21  Unnamed: 21                        800 non-null    object
 22  Unnamed: 22                        993 non-null    object
 23  Unnamed: 23                        826 non-null    object
dtypes: object(24)
memory usage: 294.1+ KB

In [5]:
new_header = df.iloc[0].str.strip()

In [6]:
df.columns = new_header

In [7]:
df = df[1:]

In [8]:
df.head()

,Portfolio,Congressional Program,Investment,Congressional Project,Sub-Project,Q#1. Sub-Project Description [BF Line],Q#6. Sub-Project Risks [BF Line],IT Tower [BF Line],IT Sub-Tower [BF Line],Cost Pool [BF Line],...,Line Item # [BF Line],Status,Strip Type,OIT Priority,SOC,Sub-Account,Type Summary,$ BY MYP Amount,$ BY OMB Submission Amount,$ BY OMB Passback Amount
1,Administrative,Corporate Operations and Maintenance,Administrative,IT Support Contracts,Ann Arbor,Ann Arbor - Location at 24 Frank Lloyd Wright ...,NaN,IT Management,IT Finance,Facilities & Power,...,45,No BY Funds,Sustainment-Steady-State,Operations and Maintenance,2328,OM,IT Support Contracts [other than PMO and Appli...,0,0,0
2,Administrative,Corporate Operations and Maintenance,Administrative,IT Support Contracts,Arlington OIT Power VA-549R-46-07,"Department of Veterans Affairs (VA), Office of...",NaN,IT Management,IT Finance,Facilities & Power,...,48,No BY Funds,Sustainment-Steady-State,Operations and Maintenance,2528,OM,IT Support Contracts [other than PMO and Appli...,0,0,0
3,Administrative,Corporate Operations and Maintenance,Administrative,IT Support Contracts,Arlington OIT VA-549R-30-02,"Department of Veterans Affairs (VA), Office of...",NaN,IT Management,IT Finance,Facilities & Power,...,46,No BY Funds,Sustainment-Steady-State,Operations and Maintenance,2328,OM,IT Support Contracts [other than PMO and Appli...,0,0,0
4,Administrative,Corporate Operations and Maintenance,Administrative,IT Support Contracts,Arlington OIT VA-549R-46-07,"Department of Veterans Affairs (VA), Office of...",NaN,IT Management,IT Finance,Facilities & Power,...,47,No BY Funds,Sustainment-Steady-State,Operations and Maintenance,2328,OM,IT Support Contracts [other than PMO and Appli...,0,0,0
5,Administrative,Corporate Operations and Maintenance,Administrative,IT Support Contracts,Common Administrative Support Services,This Service Level Agreement here in after ref...,NaN,IT Management,IT Finance,External Labor,...,28,Withdrawn,Sustainment-Steady-State,Operations and Maintenance,2311,OM,Interagency Agreement (IAA),0,0,0

In [9]:
df.iloc[0]

0
Portfolio                                                                    Administrative
Congressional Program                                  Corporate Operations and Maintenance
Investment                                                                   Administrative
Congressional Project                                                  IT Support Contracts
Sub-Project                                                                       Ann Arbor
Q#1. Sub-Project Description [BF Line]    Ann Arbor - Location at 24 Frank Lloyd Wright ...
Q#6. Sub-Project Risks [BF Line]                                                        NaN
IT Tower [BF Line]                                                            IT Management
IT Sub-Tower [BF Line]                                                           IT Finance
Cost Pool [BF Line]                                                      Facilities & Power
Cost Sub-Pool [BF Line]                                                               Lease
Service Provider                                                                       ITRM
Funding Type                                                                             BA
ID #                                                                                   1695
Line Item # [BF Line]                                                                    45
Status                                                                          No BY Funds
Strip Type                                                         Sustainment-Steady-State
OIT Priority                                                     Operations and Maintenance
SOC                                                                                    2328
Sub-Account                                                                              OM
Type Summary                              IT Support Contracts [other than PMO and Appli...
$ BY MYP Amount                                                                           0
$ BY OMB Submission Amount                                                                0
$ BY OMB Passback Amount                                                                  0
Name: 1, dtype: object

In [10]:
df.reset_index(inplace=True)

In [11]:
df.describe()

0           index
count  1567.00000
mean    784.00000
std     452.49825
min       1.00000
25%     392.50000
50%     784.00000
75%    1175.50000
max    1567.00000

In [12]:
# find the number of unique entries for each column

df.nunique()

0
index                                     1567
Portfolio                                    7
Congressional Program                       15
Investment                                  27
Congressional Project                       69
Sub-Project                               1094
Q#1. Sub-Project Description [BF Line]     997
Q#6. Sub-Project Risks [BF Line]           247
IT Tower [BF Line]                          10
IT Sub-Tower [BF Line]                      25
Cost Pool [BF Line]                          8
Cost Sub-Pool [BF Line]                     10
Service Provider                             9
Funding Type                                 4
ID #                                       143
Line Item # [BF Line]                       88
Status                                       4
Strip Type                                   6
OIT Priority                                14
SOC                                         40
Sub-Account                                  4
Type Summary                                29
$ BY MYP Amount                            499
$ BY OMB Submission Amount                 531
$ BY OMB Passback Amount                   468
dtype: int64

In [14]:
df['ind'] = df['ID #'].astype(str) + '-' + df['Line Item # [BF Line]'].astype(str)

In [15]:
df['ind']

0       1695-45
1       1695-48
2       1695-46
3       1695-47
4       1694-28
         ...
1562     1585-4
1563     1585-1
1564     1585-3
1565     1585-2
1566    nan-nan
Name: ind, Length: 1567, dtype: object

In [16]:
df['ind'].nunique()

1567

In [17]:
df[df.duplicated('ind', keep=False)]

Empty DataFrame
Columns: [index, Portfolio, Congressional Program, Investment, Congressional Project, Sub-Project, Q#1. Sub-Project Description [BF Line], Q#6. Sub-Project Risks [BF Line], IT Tower [BF Line], IT Sub-Tower [BF Line], Cost Pool [BF Line], Cost Sub-Pool [BF Line], Service Provider, Funding Type, ID #, Line Item # [BF Line], Status, Strip Type, OIT Priority, SOC, Sub-Account, Type Summary, $ BY MYP Amount, $ BY OMB Submission Amount, $ BY OMB Passback Amount, ind]
Index: []

[0 rows x 26 columns]

In [18]:
df.head()

,index,Portfolio,Congressional Program,Investment,Congressional Project,Sub-Project,Q#1. Sub-Project Description [BF Line],Q#6. Sub-Project Risks [BF Line],IT Tower [BF Line],IT Sub-Tower [BF Line],...,Status,Strip Type,OIT Priority,SOC,Sub-Account,Type Summary,$ BY MYP Amount,$ BY OMB Submission Amount,$ BY OMB Passback Amount,ind
0,1,Administrative,Corporate Operations and Maintenance,Administrative,IT Support Contracts,Ann Arbor,Ann Arbor - Location at 24 Frank Lloyd Wright ...,NaN,IT Management,IT Finance,...,No BY Funds,Sustainment-Steady-State,Operations and Maintenance,2328,OM,IT Support Contracts [other than PMO and Appli...,0,0,0,1695-45
1,2,Administrative,Corporate Operations and Maintenance,Administrative,IT Support Contracts,Arlington OIT Power VA-549R-46-07,"Department of Veterans Affairs (VA), Office of...",NaN,IT Management,IT Finance,...,No BY Funds,Sustainment-Steady-State,Operations and Maintenance,2528,OM,IT Support Contracts [other than PMO and Appli...,0,0,0,1695-48
2,3,Administrative,Corporate Operations and Maintenance,Administrative,IT Support Contracts,Arlington OIT VA-549R-30-02,"Department of Veterans Affairs (VA), Office of...",NaN,IT Management,IT Finance,...,No BY Funds,Sustainment-Steady-State,Operations and Maintenance,2328,OM,IT Support Contracts [other than PMO and Appli...,0,0,0,1695-46
3,4,Administrative,Corporate Operations and Maintenance,Administrative,IT Support Contracts,Arlington OIT VA-549R-46-07,"Department of Veterans Affairs (VA), Office of...",NaN,IT Management,IT Finance,...,No BY Funds,Sustainment-Steady-State,Operations and Maintenance,2328,OM,IT Support Contracts [other than PMO and Appli...,0,0,0,1695-47
4,5,Administrative,Corporate Operations and Maintenance,Administrative,IT Support Contracts,Common Administrative Support Services,This Service Level Agreement here in after ref...,NaN,IT Management,IT Finance,...,Withdrawn,Sustainment-Steady-State,Operations and Maintenance,2311,OM,Interagency Agreement (IAA),0,0,0,1694-28

In [45]:

# do I know what will columns will be filtered? 
# 'Status' = 'Financed'
# 'Funding Type' = 'BA'
# 'Portfolio' = 'Administrative'

In [19]:
df['Status'].unique()

array(['No BY Funds', 'Withdrawn', 'Financed', 'Submitted', nan],
      dtype=object)

In [20]:
df['Funding Type'].unique()

array(['BA', 'RA', 'EXT', 'ARP', nan], dtype=object)

In [21]:
df['Portfolio'].unique()

array(['Administrative', 'Benefits', 'Corporate', 'Enterprise', 'Health',
       'Memorial Affairs', 'Staffing (Pay)', nan], dtype=object)

In [23]:
Status = 'Financed'
Funding_Type = 'BA'
Portfolio = 'Enterprise'

In [38]:
df = df[(df['Status'] == Status) & (df['Funding Type'] == Funding_Type) & (df['Portfolio'] == Portfolio) ]

In [31]:
df.drop('index', axis = 1, inplace = True)

In [39]:
df.columns

Index(['Portfolio', 'Congressional Program', 'Investment',
       'Congressional Project', 'Sub-Project',
       'Q#1. Sub-Project Description [BF Line]',
       'Q#6. Sub-Project Risks [BF Line]', 'IT Tower [BF Line]',
       'IT Sub-Tower [BF Line]', 'Cost Pool [BF Line]',
       'Cost Sub-Pool [BF Line]', 'Service Provider', 'Funding Type', 'ID #',
       'Line Item # [BF Line]', 'Status', 'Strip Type', 'OIT Priority', 'SOC',
       'Sub-Account', 'Type Summary', '$ BY MYP Amount',
       '$ BY OMB Submission Amount', '$ BY OMB Passback Amount', 'ind'],
      dtype='object', name=0)

In [40]:
df22 = pd.DataFrame()

In [41]:
df22[['Index', 'Portfolio', 'Congressional Project', 'Sub-Project', 'Sub-Account', 'Funding']] = df[['ind', 'Portfolio', 'Congressional Project', 'Sub-Project', 'Sub-Account', '$ BY OMB Passback Amount' ]]

In [42]:
df22

,Index,Portfolio,Congressional Project,Sub-Project,Sub-Account,Funding
650,1615-1,Enterprise,Cyber Security,Identity and Access Management - Enterprise (IAM),DEV,11.2
652,1616-28,Enterprise,Data Integration and Management,ACOE Advanced Tools and Support,OM,8.175
659,1616-2,Enterprise,Data Integration and Management,Collaborative Terminology Tooling Data Management,OM,2.32
663,1616-29,Enterprise,Data Integration and Management,Data Access Services (DAS),OM,13
669,1616-78,Enterprise,Data Integration and Management,DevSecOps Advanced Tools and Support,OM,9
...,...,...,...,...,...,...
930,1582-1,Enterprise,Hardware Maintenance,Enterprise Facility Allowance,OM,0.482
941,1577-1,Enterprise,Software Maintenance,Enterprise Software License Maintenance,OM,243.983
959,1579-2,Enterprise,Telecommunications,EIS Transition,OM,18.458
960,1579-1,Enterprise,Telecommunications,Enterprise Telecommunications,OM,274.047
965,1616-83,Enterprise,Data Integration and Management,API Management,DEV,8

In [1]:
ft22pt = df22.pivot_table(values= 'Funding',aggfunc=np.sum, index= ('Congressional Project', 'Sub-Project'), columns= 'Sub-Account', fill_value=0)

NameError: name 'df22' is not defined

In [ ]:
g = df.groupby('cnpj')['bc_icms'].sum().reset_index(name='sum')